# Generated by Django 5.1.4 on 2024-12-24 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_bank', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=100)),
                ('IFSC', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
                ('document', models.FileField(null=True, upload_to='bank/')),
            ],
        ),
        migrations.CreateModel(
            name='employee_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.BooleanField(default=False, null=True)),
                ('aadhar', models.BooleanField(default=False, null=True)),
                ('job_history', models.BooleanField(default=False, null=True)),
                ('education', models.BooleanField(default=False, null=True)),
                ('family', models.BooleanField(default=False, null=True)),
                ('access_control', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('isdependent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jobhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('employee_code', models.CharField(max_length=100, null=True)),
                ('joining_date', models.DateField()),
                ('relieving_date', models.DateField()),
                ('last_CTC', models.CharField(max_length=100)),
                ('reason', models.TextField(null=True)),
                ('document', models.FileField(null=True, upload_to='job/')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Integrity_control',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile',
        ),
        migrations.AddField(
            model_name='bank',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='references',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
